#!/usr/bin/env python3
"""
This class provides utilities for the Seisflows solver interactions with
Specfem3D Cartesian.
"""
import os
import time
from glob import glob
from seisflows import logger
from seisflows.tools import unix
from seisflows.tools.specfem import setpar, getpar
from seisflows.solver.specfem import Specfem


class Specfem3D(Specfem):
    """
    Solver SPECFEM3D
    ----------------
    SPECFEM3D-specific alterations to the base SPECFEM module

    Parameters
    ----------
    :type source_prefix: str
    :param source_prefix: Prefix of source files in path SPECFEM_DATA. Must be
        in ['CMTSOLUTION', 'FORCESOLUTION']. Defaults to 'CMTSOLUTION'
    :type export_vtk: bool
    :param export_vtk: at the finalization step of each iteration, convert
        all eligible model and gradient directories in the `path_output`
        to .vtk files for visualization using ParaView (or similar programs). 
        Files are exported to `path_output`/VTK
    :type prune_scratch: bool
    :param prune_scratch: prune/remove database files as soon as they are used,
        to keep overall filesystem burden down
        - removes *.vt? files after they're generated by a forward simulation
        - removes proc*_absorb_field.bin and proc*_save_forward_array.bin
            files after adjoint simulations
    :type path_mesh_external: str
    :param path_mesh_external: PATCH (RUB/SFB1683/B04): path to a pre-built
        SPECFEM3D database directory (i.e., the `LOCAL_PATH`/OUTPUT_FILES/
        DATABASES_MPI produced once via an EXTERNAL mesher such as Cubit +
        `xdecompose_mesh`/`xgenerate_databases`), for setups that do not use
        SPECFEM3D's internal mesher (`xmeshfem3D`). The base class only
        copies `bin/` and `DATA/` into each fresh solver working directory
        and leaves `model_databases` empty, which makes `xmeshfem3D` (and
        its required `DATA/meshfem3D_files/Mesh_Par_file`) mandatory. If set,
        the pre-built `proc*_Database`/`proc*_external_mesh.bin`/model files
        are copied into the new working directory's `model_databases`
        immediately after initialization, so `forward_simulation()`'s
        existing "drop xmeshfem3D if already meshed" check
        (`glob(model_databases/proc*_Database)`) takes effect on the very
        first call too. If None (default), behaviour is unchanged from
        upstream (internal mesher expected).

    Paths
    -----
    ***
    """
    __doc__ = Specfem.__doc__ + __doc__

    def __init__(self, source_prefix="CMTSOLUTION", export_vtk=True,
                 prune_scratch=True, path_mesh_external=None, **kwargs):
        """
        Instantiate a Specfem3D_Cartesian solver interface
        
        .. note:: Repeated variables

            For variables that are expressed as both public and private (one
            leading underscore), we have a public version so that the parameter
            will show up in the parameter file, and a private one so that the 
            other SPECFEM versions can use it for boolean logic without
            necessarily needing to include it in their parameter file since it
            is not accessed and therefore not necessary.
        """

        super().__init__(source_prefix=source_prefix, **kwargs)

        self.prune_scratch = prune_scratch
        self.path_mesh_external = path_mesh_external

        # See note about repeated variables above
        self.export_vtk = export_vtk
        self._export_vtk = export_vtk

        # Overwriting the base class parameters
        self._available_materials = ["ACOUSTIC", "ELASTIC", 
                                     "TRANSVERSE_ISOTROPIC", "ANISOTROPIC"]
        self._acceptable_source_prefixes = ["CMTSOLUTION", "FORCESOLUTION"]
        self._required_binaries = ["xspecfem3D", "xmeshfem3D",
                                   "xgenerate_databases", "xcombine_sem",
                                   "xcombine_vol_data_vtk"]

        # Choose what type of smoothing to use
        if self.smooth_type == "gaussian":
            logger.warning("`smooth_type` 'gaussian' is very slow, recommend "
                           "switching to type 'pde'")
            self._required_binaries.append("xsmooth_sem")        
        elif self.smooth_type == "pde":
            
            self._required_binaries.append("xsmooth_sem_pde")
        else:
            raise NotImplementedError("`smooth_type` must be 'pde' or "
                                      "'gaussian'")
        
        # Overwriting constants that will be referenced during simulations 
        self._fwd_simulation_executables = [
            "bin/xmeshfem3D", "bin/xgenerate_databases", "bin/xspecfem3D"
            ]

        self._adj_simulation_executables = ["bin/xspecfem3D"]
        self._absorb_wildcard = "proc??????_absorb_field*"
        self._forward_array_wildcard = "proc??????_save_forward_arrays*"

        # Internally used parameters set by functions within class
        self._model_databases = None
        self.path._vtk_files = os.path.join(self.path.scratch, "vtk_files")

    def check(self):
        """SPECFEM3D_Cartesian specific check tasks"""
        super().check()

        if isinstance(self.materials, str) and \
            self.materials.upper() == "ANISOTROPIC":
            logger.warning("the 'ANISOTROPIC' material parameter is an "
                           "experimental feature that requires "
                           "a modified version of SPECFEM3D. Use at your own "
                           "risk, not guaranteed to work")

            anisotropic_kl = getpar(key="ANISOTROPIC_KL", 
                                    file=os.path.join(self.path.specfem_data, 
                                                      "Par_file"))[1]
            assert(anisotropic_kl == ".true."), (
                f"SPECFEM3D Par_file parameter 'ANISOTROPIC_KL' must be set "
                f"'.true.' for ANISOTROPIC parameters"
                )


    def setup(self):
        """
        Generate .vtk files for the initial and target (if applicable) models,
        which the User can use for external visualization
        """
        super().setup()

    def _initialize_working_directory(self, cwd=None):
        """
        PATCH (RUB/SFB1683/B04): after the base class builds a fresh solver
        working directory (which leaves `model_databases` empty, requiring
        SPECFEM3D's internal mesher `xmeshfem3D`), copy in a pre-built
        EXTERNAL mesh database (Cubit + xdecompose_mesh/xgenerate_databases)
        if `path_mesh_external` is set. This lets `forward_simulation()`'s
        existing `glob(model_databases/proc*_Database)` check correctly
        detect an already-meshed model and skip `xmeshfem3D` even on the
        very first call, instead of requiring `DATA/meshfem3D_files/
        Mesh_Par_file` (internal-mesher-only). No effect (falls back to
        upstream behaviour) if `path_mesh_external` is not set, so SPECFEM3D
        setups using the internal mesher are unaffected.
        """
        super()._initialize_working_directory(cwd=cwd)

        if not self.path_mesh_external:
            return

        if cwd is None:
            cwd = self.cwd

        src = glob(os.path.join(self.path_mesh_external, "*"))
        dst = os.path.join(cwd, self.model_databases, "")
        if src:
            logger.debug(f"[specfem3d] copying external mesh database from "
                         f"'{self.path_mesh_external}' into '{dst}'")
            unix.cp(src, dst)
        else:
            logger.warning(f"[specfem3d] `path_mesh_external`="
                           f"'{self.path_mesh_external}' matched no files")

    def data_wildcard(self, comp="?"):
        """
        Returns a wildcard identifier for synthetic data

        TODO where does SU put its component?

        :rtype: str
        :return: wildcard identifier for channels
        """
        if self.syn_data_format.upper() == "SU":
            return f"*_d?_SU"
        elif self.syn_data_format.upper() == "ASCII":
            return f"*.?X{comp}.sem?"

    @property
    def model_databases(self):
        """
        The location of databases for model outputs, usually
        OUTPUT_FILES/DATABASES_MPI. This can be determined by 'LOCAL_PATH'
        in your Par_file
        """
        if self._model_databases is None:
            self._model_databases = getpar(
                key="LOCAL_PATH", file=os.path.join(self.path.specfem_data,
                                                    "Par_file"))[1]
        return self._model_databases

    @property
    def kernel_databases(self):
        """
        The location of databases for kernel outputs, usually the same as
        'model_databases'
        """
        return self.model_databases

    def forward_simulation(self, **kwargs):
        """
        Calls SPECFEM3D forward solver, exports solver outputs to traces dir

        See `solver.specfem.forward_simulation` for info on required parameters
        """
        unix.cd(self.cwd)

        # PATCH MAX: Die alte Version schnitt bei jedem Aufruf das ERSTE
        # Element der Liste ab (`[1:]`), solange proc*_Database existiert --
        # das ist ab dem 1. Lauf IMMER der Fall. Bei jedem weiteren Aufruf von
        # forward_simulation() (z.B. Line-Search-Trial-Schritte, spaetere
        # Iterationen) wurde so ZUSAETZLICH `xgenerate_databases` entfernt --
        # genau der Schritt, der aktualisierte vp.bin/vs.bin ueberhaupt erst
        # in die kompilierte Solver-Datenbank einliest. Ab dem 2. Aufruf lief
        # nur noch xspecfem3D auf der eingefrorenen Datenbank vom 1. Lauf,
        # unabhaengig vom tatsaechlichen Modell auf der Platte -> Trial-
        # Simulationen produzierten bitidentische Synthetik/Misfit, Line
        # Search "stalled" trotz echter Modellperturbation. Fix: nur
        # `xmeshfem3D` gezielt und idempotent herausfiltern.
        if glob(os.path.join(self.model_databases, "proc*_Database")):
            self._fwd_simulation_executables = [
                exc for exc in self._fwd_simulation_executables
                if "xmeshfem3D" not in exc
            ]

        # SPECFEM3D has to deal with attenuation
        if self.attenuation:
            setpar(key="ATTENUATION", val=".true.", file="DATA/Par_file")
        else:
            setpar(key="ATTENUATION", val=".false`.", file="DATA/Par_file")

        super().forward_simulation(**kwargs)

    def adjoint_simulation(self, **kwargs):
        """
        Calls SPECFEM3D adjoint solver, creates the `SEM` folder with adjoint
        traces which is required by the adjoint solver

        See `solver.specfem.adjoint_simulation` for info on required parameters

        :type executables: list or None
        :param executables: list of SPECFEM executables to run, in order, to
            complete an adjoint simulation. This can be left None in most cases,
            which will select default values based on the specific solver
            being called (2D/3D/3D_GLOBE). It is made an optional parameter
            to keep the function more general for inheritance purposes.
        """
        # Make sure attenuation is OFF, if ON you'll get a floating point error
        unix.cd(self.cwd)
        setpar(key="ATTENUATION", val=".false.", file="DATA/Par_file")

        # Make sure we have a STATIONS_ADJOINT file. Simply copy STATIONS file
        # we expect that preprocessing has created ALL required adjoint sources
        dst = os.path.join(self.cwd, "DATA", "STATIONS_ADJOINT")
        if not os.path.exists(dst):
            src = os.path.join(self.cwd, "DATA", "STATIONS")
            unix.cp(src, dst)

        # SPECFEM class takes care of `simulation_type`` and `save_forward`` 
        # params as well as kernel renaming and export and scratch pruning
        super().adjoint_simulation(**kwargs)

    def combine_vol_data_vtk(self, input_path, output_path, hi_res=False,
                             parameters=None):
        """
        Wrapper for 'xcombine_vol_data_vtk'. Combines binary files together
        to generate a single .VTK file that can be visualized by external
        software like ParaView

        .. rubric::
            xcombine_data start end quantity input_dir output_dir hi/lo-res

        .. note::
            It is ASSUMED that this function is being called by
            system.run(single=True) so that we can use the main solver
            directory to perform the kernel summation task

        :type input_path: str
        :param input_path: path to database files to be summed.
        :type output_path: strs
        :param output_path: path to export the outputs of the binary
        :type hi_res: bool
        :param hi_res: Set the high resolution flag to 1 or True, which will
            generate .vtk files with data at EACH GLL point, rather than at each
            nodal vertex. These files are LARGE, and we discourage using
            `hi_res`==True unless you know you want these files.
        :type parameters: list
        :param parameters: optional list of parameters,
            defaults to `self._parameters`
        """
        unix.cd(self.cwd)

        if parameters is None:
            parameters = self._parameters

        if not os.path.exists(output_path):
            unix.mkdir(output_path)

        # Call on xcombine_sem to combine kernels into a single file
        for name in parameters:
            # e.g.:  bin/xcombine_vol_data_vtk 0 3 alpha_kernel in/ out/ 0
            exc = f"bin/xcombine_vol_data_vtk 0 {self.nproc-1} {name} " \
                  f"{input_path} {output_path} {int(hi_res)}"
            # e.g., smooth_vp.log
            stdout = f"{self._exc2log(exc)}_{name}.log"
            self._run_binary(executable=exc, stdout=stdout, with_mpi=False)

