name: seisflows
channels:
  - conda-forge
dependencies:
  - python=3.9
  - obspy
  - cartopy
  - pyyaml
  - "pypdf<4"
  - spyder=6.0.4
  - pip
  - pip:
      - git+https://github.com/adjtomo/pyatoa.git
      - pysep-adjtomo
      - .

